config/routes.rb
Rails.application.routes.draw do
  
  resources :tutors
  resources :users

  root 'home#index'

  get '/login_tutor', to: 'tutor_sessions#new',as: :login_tutor
  post '/login_tutor', to: 'tutor_sessions#create'
  get 'tutors/:id/my_page', to: 'tutors#my_page', as: :my_page

  delete 'logout', to: 'tutor_sessions#destroy', as: 'logout'
  

  get '/login_user', to: 'user_sessions#new',as: :login_user
  post '/login_user', to: 'user_sessions#create'
  post "/schedule_session", to: "tutors#schedule_session", as: :schedule_session
  post "/cancel_session",to: "tutors#cancel_session", as: :cancel_session
  delete 'logout_user', to: 'user_sessions#destroy', as: 'user_logout'
  post 'dismiss_notifications', to: 'user_sessions#dismiss_notifications', as: 'dismiss_notifications'


  post "/make_available", to: "tutors#make_available", as: :available_session
  post "/make_unavailable", to: "tutors#make_unavailable", as: :unavailable_session
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  has_secure_password
  has_many :event_tutors
  has_many :events, through: :event_tutors
  has_many :tutoring_sessions
  has_many :users, through: :tutoring_sessions 
  belongs_to :city
  has_one_attached :photo

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, length: { in: 6..10 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :subjects, presence: true
  validates :age, presence: true
  validates :education_level, presence: true


  def city_id=(arr)

    city=City.find_or_create_by(name: arr[:name],state: arr[:state])
    self.city=city
  end

  def self.get_subjects
    Tutor.all.map{|subject| subject.subjects.downcase}.join(',').split(/[^\w-]+/).uniq
  end

  def get_subjects
    self.subjects.downcase.split(/[^\w-]+/)
  end


  def full_name
    self.first_name+" "+self.last_name
  end

  def show_tutoring_sessions
    hours=["1200","1330","1500","1630","1800"]
  end


end

app/controllers/tutors_controller.rb
# frozen_string_literal: true

class TutorsController < ApplicationController
  before_action :find_tutor_id, only: %i[show edit update destroy my_page]
  before_action :cities_states

  def index
    @my_city_tutors = Tutor.select { |tutor| tutor.city == current_user.city }
    @tutors = Tutor.all
    if params[:search].present?
      the_state = params[:search][:state]
      the_city = params[:search][:city]
      all_subjects = params[:search][:subjects]

      flash[:state] = the_state
      flash[:city] = the_city
      flash[:subjects] = all_subjects

      if !the_state.empty? && !the_city.empty? && !all_subjects.reject(&:empty?).empty?
        all_states = City.where('state ILIKE ?', the_state)
        all_cities = all_states.where('name ILIKE ?', the_city)
        if all_cities.empty?
          @tutors = nil
        else
          @tutors = all_cities.first.tutors.select { |tutors| all_subjects.reject(&:empty?).all? { |str| tutors.subjects.downcase.include? str } }

        end

      elsif !the_state.empty? && !the_city.empty? && all_subjects.reject(&:empty?).empty?
        all_states = City.where('state ILIKE ?', the_state)
        all_cities = all_states.where('name ILIKE ?', the_city)
        @tutors = if all_cities.empty?
                    nil
                  else
                    all_cities.first.tutors
                  end
      elsif !the_state.empty? && the_city.empty? && !all_subjects.reject(&:empty?).empty?
        all_states = City.where('state ILIKE ?', the_state)
        @tutors = all_states.map { |state| state.tutors.select { |tutors| all_subjects.reject(&:empty?).all? { |str| tutors.subjects.downcase.include? str } } }.flatten.compact

      elsif the_state.empty? && !the_city.empty? && !all_subjects.reject(&:empty?).empty?
        all_cities = City.where('name ILIKE ?', the_city)
        @tutors = all_cities.map { |city| city.tutors.select { |tutors| all_subjects.reject(&:empty?).all? { |str| tutors.subjects.downcase.include? str } } }.flatten.compact

      elsif !the_state.empty? && the_city.empty? && all_subjects.reject(&:empty?).empty?
        all_states = City.where('state ILIKE ?', the_state)
        @tutors = all_states.map(&:tutors).flatten

      elsif the_state.empty? && !the_city.empty? && all_subjects.reject(&:empty?).empty?
        all_cities = City.where('name ILIKE ?', the_city)
        @tutors = all_cities.map(&:tutors).flatten

      elsif the_state.empty? && the_city.empty? && !all_subjects.reject(&:empty?).empty?
        @tutors = Tutor.select { |tutors| all_subjects.reject(&:empty?).all? { |str| tutors.subjects.downcase.include? str } }
      else
        @tutors = Tutor.all

      end
    end
  end

  def new
    @tutor = Tutor.new
    @errors = flash[:errors]
  end

  def create
    @tutor = Tutor.create(tutor_params)
    if @tutor.valid?
      log_tutor_in(@tutor)
      redirect_to my_page_path(@tutor)
    else
      flash[:errors] = @tutor.errors.full_messages
      redirect_to new_tutor_path
    end
  end

  def schedule_session
    @tutoring_session = TutoringSession.create(tutoring_session_params)
    redirect_back(fallback_location: current_user)
  end

  def cancel_session
    @tutoring_session = TutoringSession.find(params[:tutoring_session_id])
    if params[:by_tutor]
      session[:notification] << [@tutoring_session.user_id, "#{@tutoring_session.tutor.full_name} canceled your reservation for #{@tutoring_session.start_time.utc.strftime('%H:%M')} "]
    end
    @tutoring_session.destroy
    redirect_back(fallback_location: current_user)
  end

  def edit
    @city = City.find_by(id: @tutor.city_id)
    @errors = flash[:errors]
  end

  def show
    # return head(:forbidden) unless @tutor == current_tutor
  end

  def update
    @tutor.update(tutor_params)
    if @tutor.save
      redirect_to @tutor
    else
      render :edit
    end
  end

  def my_page; end

  def make_available
    @tutoring_session = TutoringSession.find(params[:tutoring_session_id])
    @tutoring_session.destroy
    redirect_to my_page_path(current_tutor)
  end

  def make_unavailable
    # @tutoring_session=TutoringSession.create(tutoring_session_params)
    @tutoring_session = TutoringSession.create(start_time: params[:tutoring_sessions][:start_time], tutor_id: params[:tutoring_sessions][:tutor_id], duration: params[:tutoring_sessions][:duration])
    redirect_to my_page_path(current_tutor)
  end

  private

  def find_tutor_id
    @tutor = Tutor.find(params[:id])
  end

  def tutor_params
    params.require(:tutor).permit(:username, :password, :password_confirmation, :first_name, :last_name, :age, :education_level, :subjects, :address, :photo, city_id: %i[name state])
  end

  def cities_states
    @cities = CS.states(:us).keys.flat_map { |state| CS.cities(state, :us) }.uniq
    @states = CS.states(:us).values
  end

  def tutoring_session_params
    params.require(:tutoring_sessions).permit(:user_id, :tutor_id, :start_time, :duration)
  end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/edit.html.erb
<h1 class="edit_text_form">Edit Info</h1>
<div class="forms_centering">
<% if @errors %>
    <ul>
        <% @errors.each do |error|%>
            <li style="color:blue;"><%= error %></li>
        <%end %>
    </ul>
<% end%>

<%=form_for @tutor, html: { class: "form_container_edit" } do |f|%>
<h1>Authorization Info</h1>
    <div class="user_auth">
    
        <div>
        <%= f.label :username%>
        <%= f.text_field :username %>
        </div>

    <div style="flex-direction:row; gap:20px;">
        <div>
        <%= f.label :password%>
        <%= f.password_field :password %>
        </div>

        <div>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation %>
        </div>
    </div>
    </div>
    <h1>Personal Info</h1>
    <div class="user_auth">
        <div style="flex-direction:row; gap:20px;">
        <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
        </div>

        <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
        </div>
        
        <div>
            <%= f.label :age %>
            <%= f.number_field :age %>
        </div>
        </div>
        <div style="flex-direction:row; gap:20px;">
        <div>
            <%= f.label :education_level %>
            <%= f.text_field :education_level %>
        </div>

        <div>
        <%= f.label :subjects %>
        <%= f.text_field :subjects%>
        </div>
        </div>
        </div>
    <h1>Address Info</h1>
        <div class="user_auth">
            <div>
                <%= f.label :address %>
                <%= f.text_field :address%>
            </div>
                <%= f.fields_for :city_id do |c| %>
            <div>
            <div style="flex-direction:row; gap:20px;">
            <div>
                <%= c.label :name, "City"%>
                <%= c.text_field :name, value:"#{@city.name}", list: "cities_autocomplete" %>
                <datalist id="cities_autocomplete">
                    <% @cities.each do |city| %>
                    <option value="<%= city %>">
                    <% end %>
                </datalist>
                </div>

                <div>
                    <%= c.label :state %>
                    <%= c.text_field :state,value:"#{@city.state}", list: "state_autocomplete" %>
                <datalist id="state_autocomplete">
                    <% @states.each do |state| %>
                    <option value="<%= state %>">
                    <% end %>
                </datalist>
                </div>
                </div>
            <% end%>
            <%= f.submit "Submit", class: "my_buttons" %>
            <% end%>
        </div>
    </div>
</div>

app/views/tutors/index.html.erb
<div class="form_container"><%= simple_form_for :search, url: tutors_path, method: "GET", html: { class: 'form-horizontal form-group' } do |f| %>
    <div class="city_state_filter">
      <div id="state_filter">
        <%= f.label :state , required: false ,class:"mr-3" %>
        <%= f.input :state, input_html: {value: ""},input_html: {list:"states_autocomplete"},label: false ,required: false%>
        <datalist id="states_autocomplete">
          <% City.all.map{|ins| ins.state}.uniq.each do |state| %>
            <option value="<%= state %>">
            <% end %>
          </datalist>
        </div>
        <div id="city_filter">
          <%= f.label :city,required:false, class:"mr-3" %>
          <%= f.input :city, input_html: {value: ""},input_html: {list:"cities_autocomplete"},label:false, required: false%>
          <datalist id="cities_autocomplete">
            <% City.all.map{|ins| ins.name}.uniq.each do |city| %>
              <option value="<%= city %>">
              <% end %>
            </datalist>
          </div>
        </div>
        <hr>
        <%=f.label :subjects ,required:false  %>
        <%= f.input :subjects,  collection: Tutor.get_subjects, as: :check_boxes, input_html: {class: "checkbox-inline"},item_label_class: 'check_labels',label: false, required: false %>
        <hr>
        <div class="clear_submit_buttons">
          <%= f.submit "Search", class: "my_buttons" %>
          <%= button_to "Clear Filter", tutors_path, method: :get ,class: "my_buttons_1",id: "clear_filter"%>
        </div>
      <% end %>
    </div>
    <% if !@my_city_tutors.nil?%>
      <% if !@my_city_tutors.empty?%>
        <div class="container_for_tutors">
          <div class="tutors_your_city">
            <h4>Tutors in <%= current_user.city.name %>, <%= current_user.city.state_code %></h4>
            <p><%= @my_city_tutors.count %> Tutors in your city.</p>
          </div>
          <div class="tutors_flexes1">
            <% @my_city_tutors.each do |tutor| %>
              <div class="flip-card1">
                <div class="flip-card-inner1">
                  <div class="flip-card-front1">
                    <% if tutor.photo.attached? %>
                      <img class="avatar_photo" src="<%= (url_for(tutor.photo)) %>" alt="Avatar" style="width:200px;height:200px;">
                      <h4 class="tutors_names1"><%= tutor.full_name %>  <span style="color:#fc8973;"><%= tutor.age %></span></h4>
                    <% else%>
                      <img class="avatar_photo" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar" style="width:200px;height:200px;">
                      <h4 class="tutors_names1"><%= tutor.full_name %></h4>
                    <% end%>
                  </div>
                  <div class="flip-card-back1">
                    <h5><%= tutor.full_name %></h5>
                    <p><%= tutor.city.name %>, <%= tutor.city.state_code %></p>
                    <%= button_to "Schedule",tutor ,class: "my_buttons_2" , method: :get%>
                  </div>
                </div>
              </div>
            <% end%>
          </div>
        </div>
      <% else %>
        <h1 class="Tutors_nothing_show">There's nothing to show!</h1>
      <% end %>
    <% else %>
      <h1 clss="Tutors_nothing_show">There's nothing to show!</h1>
    <% end%>
    <hr style="margin:20px;">
    <% if !@tutors.nil?%>
      <% if !@tutors.empty?%>
        <div class="tutors_flexes">
          <% @tutors.each do |tutor| %>
            <div class="flip-card">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <% if tutor.photo.attached? %>
                    <img class="avatar_photo" src="<%= (url_for(tutor.photo)) %>" alt="Avatar" style="width:200px;height:200px;">
                    <h4 class="tutors_names"><%= tutor.full_name %> <span style="color:#fc8973;"><%= tutor.age %></span></h4>
                  <% else%>
                    <img class="avatar_photo" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar" style="width:200px;height:200px;">
                    <h4 class="tutors_names"><%= tutor.full_name %></h4>
                  <% end%>
                </div>
                <div class="flip-card-back">
                  <h5><%= tutor.full_name %></h5>
                  <p><%= tutor.city.name %>, <%= tutor.city.state_code %></p>
                  <%= button_to "Schedule",tutor ,class: "my_buttons_2" , method: :get%>
                </div>
              </div>
            </div>
          <% end%>
        </div>
      <% else %>
        <h1 class="Tutors_nothing_show">There's nothing to show!</h1>
      <% end %>
    <% else %>
      <h1 clss="Tutors_nothing_show">There's nothing to show!</h1>
    <% end%>

app/views/tutors/my_page.html.erb
<div class="tutors_schedule_page">
  <div class="tutors_schedule_inner_page">
    <% if @tutor.photo.attached? %>
      <img class="avatar_photo" src="<%= (url_for(@tutor.photo)) %>" alt="Avatar" style="width:150px;height:150px;">
    <% else%>
      <img class="avatar_photo" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar" style="width:200px;height:200px;">
    <% end%>
    <div style="margin-left:40px;">
      <h1 id="tutor_full_name"><%= @tutor.full_name %></h1>
      <h3><%= @tutor.city.name %>, <%=@tutor.city.state_code%></h3>
      <h4 style="color:grey;"><%= @tutor.education_level %></h4>
    </div>
  </div>
  <%= button_to "Edit info", edit_tutor_path(@tutor), method: :get,class:"my_buttons_1"%>
</div>
</div>
<hr>
<div class="day_of_week">
  <h1>Upcoming Tutoring Sessions</h1>
</div>
<% timenow=DateTime.now %>
<% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
<% checked_value=TutoringSession.where("start_time >= ?", timenow)%>
<% upcoming_session=checked_value.where(tutor_id:@tutor) %>
<% count=0%>
<% if !upcoming_session.empty?%>
  <% upcoming_session.each do |tutoring_session|%>
    <% if tutoring_session.user != nil%>
      <div class="tutoring_sessions_times">
        <div class="tutoring_session_name_photo">
          <% if tutoring_session.tutor.photo.attached? %>
            <img class="avatar_photo_smaller" src="<%= (url_for(tutoring_session.user.photo)) %>" alt="Avatar">
          <% else%>
            <img class="avatar_photo_smaller" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
          <% end%>
          <h1><%= tutoring_session.user.full_name %></h1>
        </div>
        <h1><%= tutoring_session.start_time.utc.strftime("%A, ") %> at <%= tutoring_session.start_time.utc.strftime("%H:%M") %></h1>
        <%= button_to "Cancel", cancel_session_path, method: :post,params:{tutoring_session_id: tutoring_session.id,by_tutor:true},class:"cancel_button"%>
      </div>
    <% else%>
      <% count+=1 %>
    <% end%>
  <% end%>
<% else%>
  <div class="tutoring_sessions_times">
    <h1 style="margin:auto; color:#e8e4e1;">No Upcoming Tutoring Sessions</h1>
  </div>
<% end%>
<% if count<0%>
  <div class="tutoring_sessions_times">
    <h1 style="margin:auto; color:#e8e4e1;">No Upcoming Tutoring Sessions</h1>
  </div>
<% end%>
<div class="previous_tutoring_sessions">
  <h1>Previous Tutoring Sessions</h1>
</div>
<% timenow=DateTime.now %>
<% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
<% checked_value=TutoringSession.where("start_time < ?", timenow)%>
<% upcoming_session=checked_value.where(tutor_id:@tutor) %>
<% upcoming_session.each do |tutoring_session|%>
  <% if tutoring_session.user != nil%>
    <div class="tutoring_sessions_times">
      <div class="tutoring_session_name_photo">
        <% if tutoring_session.user.photo.attached? %>
          <img class="avatar_photo_smaller" src="<%= (url_for(tutoring_session.user.photo)) %>" alt="Avatar">
        <% else%>
          <img class="avatar_photo_smaller" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
        <% end%>
        <h1><%= tutoring_session.user.full_name %></h1>
      </div>
      <h1><%= tutoring_session.start_time.utc.strftime("%A, %B %-d") %> at <%= tutoring_session.start_time.utc.strftime("%H:%M") %></h1>
    </div>
  <% end%>
<% end%>
<% n=1 %>
<% d=Date.today%>
<% while n<=8 do %>
  <div class="day_of_week">
    <h4 style="align-self:center;">Timeslots</h4>
    <% if n==1%>
      <h1>Today</h1>
    <%else%>
      <h1><%= d.strftime("%A") %></h1>
    <% end%>
    <h4 style="align-self:center;"><%= d %></h4>
  </div>
  <% if d.strftime("%A") != "Saturday" && d.strftime("%A") != "Sunday"%>
    <% @tutor.show_tutoring_sessions.each do |hour|%>
      <% h=hour[0,2] %>
      <% m=hour[2,4]%>
      <div class="tutoring_sessions_times">
        <% start_hour=DateTime.new(d.year,d.month,d.day,h.to_i,m.to_i) %>
        <% timenow=DateTime.now %>
        <% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
        <% checked_value=TutoringSession.find_by(start_time:start_hour,tutor_id:@tutor.id ) %>
        <% if start_hour >= timenow%>
          <% if checked_value%>
            <% if checked_value.user != nil%>
              <h1><%=h+":"+m %></h1>
              <h1 class="reserved_by">RESERVED</h1>
            <% else%>
              <h1><%=h+":"+m %></h1>
              <h1 class="timeslot_passed"> You're unavailable</h1>
              <%= button_to "Make available", available_session_path, method: :post,params:{tutoring_session_id: checked_value.id},class:"make_available"%>
            <% end%>
          <% else%>
            <h1><%=h+":"+m %></h1>
            <%= button_to "Make unavailable", unavailable_session_path, method: :post,params:{tutoring_sessions:{tutor_id:@tutor.id , start_time:start_hour, duration:60  }},class:"make_unavailable"%>
          <% end%>
        <% else%>
          <h1><%=h+":"+m %></h1>
          <h1 class="timeslot_passed"> This timeslot passed.</h1>
        <% end%>
      </div>
    <% end%>
  <% else%>
    <div class="tutoring_sessions_times">
      <h1 style="margin:auto; color:#e8e4e1;">Tutors are off on the weekends!</h1>
    </div>
  <% end%>
  <% d+=1%>
  <% n+=1 %>
<% end%>

app/views/tutors/new.html.erb
<%= render "/nav/navbar" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>



<h1 class="edit_text_form">Register to Teach!</h1>
<% if @errors %>
    <ul id="errors_flash">
        <% @errors.each do |error|%>
            <li class="errors_flash"><%= error %></li>
        <%end %>
    </ul>
<% end%>
<div class="forms_centering">


        <%=form_for @tutor, html: { class: "form_container_edit" } do |f|%>
        <h1>Authorization Info</h1>
        
        <div class="user_auth">
             <div>
            <%= f.label :username%>
            <%= f.text_field :username %>
            </div>

        <div style="flex-direction:row; gap:20px;"> 
            <div>
            <%= f.label :password%>
            <%= f.password_field :password %>
            </div>

            <div>
            <%= f.label :password_confirmation%>
            <%= f.password_field :password_confirmation %>
            </div>
        </div>
        </div>

        <h1>Personal Info</h1>
        <div class="user_auth">
            <div style="flex-direction:row; gap:20px;">
                <div>
                <%= f.label :first_name %>
                <%= f.text_field :first_name %>
                </div>

                <div>
                <%= f.label :last_name %>
                <%= f.text_field :last_name %>
                </div>

                <div>
                <%= f.label :age %>
                <%= f.number_field :age %>
                </div>
            </div>

            <div style="flex-direction:row; gap:20px;">
                <div>
                <%= f.label :education_level %>
                <%= f.text_field :education_level %>
                </div>

                <div>
                <%= f.label :subjects %>
                <%= f.text_field :subjects %>
                </div>
            </div>
        </div>
                
            <h1>Address Info</h1>
        <div class="user_auth">
            <div>
            <%= f.label :address %>
            <%= f.text_field :address %>
        </div>

            <%= f.fields_for :city_id do |c| %>
            <div>
                <div style="flex-direction:row; gap:20px;">
                    <div>
                    <%= c.label :name, "City"%>
                    <%= c.text_field :name, list: "cities_autocomplete" %>
                    <datalist id="cities_autocomplete">
                        <% @cities.each do |city| %>
                        <option value="<%= city %>">
                    <% end %>
                    </datalist>
                    </div>

                    <div>    
                    <%= c.label :state %>
                    <%= c.text_field :state, list: "state_autocomplete" %>
                    <datalist id="state_autocomplete">
                        <% @states.each do |state| %>
                        <option value="<%= state %>">
                        <% end %>
                    </datalist>
                    </div>
                </div>
            <% end%>
            <div>
            <h1 style="margin-bottom:30px;">Profile Photo</h1>

            <div class="photo_submit">
            <%= f.file_field :photo %>
            </div>
            </div>
            <div style="margin-top:30px;">
            <%= f.submit "Submit", class: "my_buttons" %>
            </div>
        <% end%>
      </div>
    </div>
</div>

app/views/tutors/show.html.erb
<div class="tutors_schedule_page">
  <div class="tutors_schedule_inner_page">
    <% if @tutor.photo.attached? %>
      <img class="avatar_photo" src="<%= (url_for(@tutor.photo)) %>" alt="Avatar" style="width:150px;height:150px;">
    <% else%>
      <img class="avatar_photo" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar" style="width:200px;height:200px;">
    <% end%>
    <div style="margin-left:40px;">
      <h1 id="tutor_full_name"><%= @tutor.full_name %></h1>
      <h3><%= @tutor.city.name %>, <%=@tutor.city.state_code%></h3>
      <h4 style="color:grey;"><%= @tutor.education_level %></h4>
    </div>
  </div>
  <div class="subject_tags">
    <h3>Subjects</h3>
    <div class="subject_tags_inner">
      <% @tutor.get_subjects.each do |subject|%>
        <h3 class="inner_subject_tags"><%=subject%></h3>
      <% end%>
    </div>
  </div>
</div>
<hr>
<% n=0 %>
<% d=Date.today%>
<% while n<=7 do %>
  <div class="day_of_week">
    <h4 style="align-self:center;">Timeslots</h4>
    <% if n==0%>
      <h1>Today</h1>
    <%else%>
      <h1><%= d.strftime("%A") %></h1>
    <% end%>
    <h4 style="align-self:center;"><%= d %></h4>
  </div>
  <% if d.strftime("%A") != "Saturday" && d.strftime("%A") != "Sunday"%>
    <% @tutor.show_tutoring_sessions.each do |hour|%>
      <% h=hour[0,2] %>
      <% m=hour[2,4]%>
      <div class="tutoring_sessions_times">
        <% start_hour=DateTime.new(d.year,d.month,d.day,h.to_i,m.to_i) %>
        <% timenow=DateTime.now %>
        <% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
        <% checked_value=TutoringSession.find_by(start_time:start_hour,tutor_id:@tutor.id ) %>
        <% if start_hour >= timenow%>
          <% if checked_value%>
            <% if checked_value.user==current_user%>
              <h1 class="cancel_by_me"><%=h+":"+m %></h1>
              <h1 class="reserved_by_you">Reserved by You</h1>
              <%= button_to "Cancel", cancel_session_path, method: :post,params:{tutoring_session_id: checked_value.id},class:"cancel_button"%>
            <% elsif checked_value.user==nil%>
              <h1><%=h+":"+m %></h1>
              <h1 class="timeslot_passed"> Tutor is not available!</h1>
            <% else%>
              <h1><%=h+":"+m %></h1>
              <h1 class="reserved_by">RESERVED</h1>
            <% end%>
          <% else%>
            <h1><%=h+":"+m %></h1>
            <%= button_to "Schedule", schedule_session_path, method: :post,params:{tutoring_sessions:{user_id: current_user.id,tutor_id:@tutor.id , start_time:start_hour, duration:60  }},class:"my_buttons_1"%>
          <% end%>
        <% else%>
          <h1><%=h+":"+m %></h1>
          <h1 class="timeslot_passed"> This timeslot passed.</h1>
        <% end%>
      </div>
    <% end%>
  <% else%>
    <div class="tutoring_sessions_times">
      <h1 style="margin:auto; color:#e8e4e1;">Tutors are off on the weekends!</h1>
    </div>
  <% end%>
  <% d+=1%>
  <% n+=1 %>
<% end%>