config/routes.rb
Rails.application.routes.draw do
  
  resources :tutors
  resources :users

  root 'home#index'

  get '/login_tutor', to: 'tutor_sessions#new',as: :login_tutor
  post '/login_tutor', to: 'tutor_sessions#create'
  get 'tutors/:id/my_page', to: 'tutors#my_page', as: :my_page

  delete 'logout', to: 'tutor_sessions#destroy', as: 'logout'
  

  get '/login_user', to: 'user_sessions#new',as: :login_user
  post '/login_user', to: 'user_sessions#create'
  post "/schedule_session", to: "tutors#schedule_session", as: :schedule_session
  post "/cancel_session",to: "tutors#cancel_session", as: :cancel_session
  delete 'logout_user', to: 'user_sessions#destroy', as: 'user_logout'
  post 'dismiss_notifications', to: 'user_sessions#dismiss_notifications', as: 'dismiss_notifications'


  post "/make_available", to: "tutors#make_available", as: :available_session
  post "/make_unavailable", to: "tutors#make_unavailable", as: :unavailable_session
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tutoring_sessions
  has_many :tutors, through: :tutoring_sessions
  has_many :events
  belongs_to :city
  has_one_attached :photo


  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, length: { in: 6..10 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :occupation, presence: true
  validates :address, presence: true
  




  def city_id=(arr)
    city=City.find_or_create_by(name: arr[:name],state: arr[:state])
    self.city=city
  end

  def full_name
    self.first_name+" "+self.last_name
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user_id, only:[:show,:edit,:update,:destroy]
    before_action :cities_states

    


    def new
        @user=User.new
        @errors=flash[:errors]
    end

    def create
        byebug
        @user=User.new(user_params)
        if @user.save
            log_user_in(@user)
            redirect_to @user
        else
            flash[:errors]=@user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
        @city=City.find_by(id:@user.city_id)
        @errors=flash[:errors]
    end

    def show         

    end

    def update
        @user.update(user_params)
        if @user.save
            redirect_to @user
        else
            render :edit
        end
    end

    private 
    def find_user_id
        @user=User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username,:password,:password_confirmation,:first_name,:last_name,:age,:occupation,:grade,:address,:photo,city_id:[:name,:state])
    end

    def cities_states
        @cities=CS.states(:us).keys.flat_map { |state| CS.cities(state, :us) }.uniq
        @states=CS.states(:us).values
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1 class="edit_text_form">Edit Info</h1>
<div class="forms_centering">
<% if @errors %>
    <ul>
        <% @errors.each do |error|%>
            <li style="color:blue;"><%= error %></li>
        <%end %>
    </ul>
<% end%>

<%=form_for @user, html: { class: "form_container_edit" } do |f|%>
<h1>Authorization Info</h1>
    <div class="user_auth">
    
        <div>
        <%= f.label :username%>
        <%= f.text_field :username %>
        </div>

    <div style="flex-direction:row; gap:20px;">
        <div>
        <%= f.label :password%>
        <%= f.password_field :password %>
        </div>

        <div>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation %>
        </div>
    </div>
    </div>
    <h1>Personal Info</h1>
    <div class="user_auth">
        <div style="flex-direction:row; gap:20px;">
        <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
        </div>

        <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
        </div>
        
        <div>
            <%= f.label :age %>
            <%= f.number_field :age %>
        </div>
        </div>
        <div style="flex-direction:row; gap:20px;">
        <div>
            <%= f.label :occupation %>
            <%= f.text_field :occupation %>
        </div>

        <div>
        <%= f.label :grade %>
        <%= f.text_field :grade%>
        </div>
        </div>
        </div>
    <h1>Address Info</h1>
        <div class="user_auth">
            <div>
                <%= f.label :address %>
                <%= f.text_field :address%>
            </div>
                <%= f.fields_for :city_id do |c| %>
            <div>
            <div style="flex-direction:row; gap:20px;">
            <div>
                <%= c.label :name, "City"%>
                <%= c.text_field :name, value:"#{@city.name}", list: "cities_autocomplete" %>
                <datalist id="cities_autocomplete">
                    <% @cities.each do |city| %>
                    <option value="<%= city %>">
                    <% end %>
                </datalist>
                </div>

                <div>
                    <%= c.label :state %>
                    <%= c.text_field :state,value:"#{@city.state}", list: "state_autocomplete" %>
                <datalist id="state_autocomplete">
                    <% @states.each do |state| %>
                    <option value="<%= state %>">
                    <% end %>
                </datalist>
                </div>
                </div>
            <% end%>
            <%= f.submit "Submit", class: "my_buttons" %>
            <% end%>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%= render "/nav/navbar" %>

<h1 class="edit_text_form">Register to Learn!</h1>
<% if @errors %>
    <ul id="errors_flash">
        <% @errors.each do |error|%>
            <li class="errors_flash"><%= error %></li>
        <%end %>
    </ul>
<% end%>
<div class="forms_centering">


        <%=form_for @user, html: { class: "form_container_edit" } do |f|%>
        <h1>Authorization Info</h1>
        
        <div class="user_auth">
             <div>
            <%= f.label :username%>
            <%= f.text_field :username %>
            </div>

        <div style="flex-direction:row; gap:20px;"> 
            <div>
            <%= f.label :password%>
            <%= f.password_field :password %>
            </div>

            <div>
            <%= f.label :password_confirmation%>
            <%= f.password_field :password_confirmation %>
            </div>
        </div>
        </div>

        <h1>Personal Info</h1>
        <div class="user_auth">
            <div style="flex-direction:row; gap:20px;">
                <div>
                <%= f.label :first_name %>
                <%= f.text_field :first_name %>
                </div>

                <div>
                <%= f.label :last_name %>
                <%= f.text_field :last_name %>
                </div>

                <div>
                <%= f.label :age %>
                <%= f.number_field :age %>
                </div>
            </div>

            <div style="flex-direction:row; gap:20px;">
                <div>
                <%= f.label :occupation %>
                <%= f.text_field :occupation %>
                </div>

                <div>
                <%= f.label :grade %>
                <%= f.text_field :grade ,placeholder:"optional"%>
                </div>
            </div>
        </div>

    <h1>Address Info</h1>
        <div class="user_auth">
            <div>
            <%= f.label :address %>
            <%= f.text_field :address %>
        </div>

            <%= f.fields_for :city_id do |c| %>
            <div>
                <div style="flex-direction:row; gap:20px;">
                    <div>
                    <%= c.label :name, "City"%>
                    <%= c.text_field :name, list: "cities_autocomplete" %>
                    <datalist id="cities_autocomplete">
                        <% @cities.each do |city| %>
                        <option value="<%= city %>">
                    <% end %>
                    </datalist>
                    </div>

                    <div>    
                    <%= c.label :state %>
                    <%= c.text_field :state, list: "state_autocomplete" %>
                    <datalist id="state_autocomplete">
                        <% @states.each do |state| %>
                        <option value="<%= state %>">
                        <% end %>
                    </datalist>
                    </div>
                </div>
            <% end%>
            <div>
            <h1 style="margin-bottom:30px;">Profile Photo</h1>

            <div class="photo_submit">
            <%= f.file_field :photo %>
            </div>
            </div>
            <div style="margin-top:30px;">
            <%= f.submit "Submit", class: "my_buttons" %>
            </div>
        <% end%>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<hr>
<div class="tutors_schedule_page">
  <div class="tutors_schedule_inner_page">
    <% if @user.photo.attached? %>
      <img class="avatar_photo" src="<%= (url_for(@user.photo)) %>" alt="Avatar" style="width:150px;height:150px;">
    <% else%>
      <img class="avatar_photo" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar" style="width:200px;height:200px;">
    <% end%>
    <div style="margin-left:40px;">
      <h1 id="tutor_full_name"><%= @user.full_name %></h1>
      <h3><%= @user.city.name %>, <%=@user.city.state_code%></h3>
      <h4 style="color:grey;"><%= @user.occupation %></h4>
    </div>
  </div>
  <%= button_to "Edit info", edit_user_path(@user), method: :get,class:"my_buttons_1"%>
</div>
</div>
<hr>
<% if session[:notification]%>
  <% session[:notification].each do |noti|%>
    <% if noti[0]==current_user.id%>
      <div class="notifications">
        <p><%= noti[1] %></p>
        <%= link_to 'X', dismiss_notifications_path(noti), method: :post %>
      </div>
    <% end%>
  <% end%>
<% end%>
<div class="day_of_week">
  <h1>Upcoming Tutoring Sessions</h1>
</div>
<% timenow=DateTime.now %>
<% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
<% checked_value=TutoringSession.where("start_time >= ?", timenow)%>
<% upcoming_session=checked_value.where(user_id:@user) %>
<% upcoming_session.each do |tutoring_session|%>
  <div class="tutoring_sessions_times">
    <div class="tutoring_session_name_photo">
      <% if tutoring_session.tutor.photo.attached? %>
        <img class="avatar_photo_smaller" src="<%= (url_for(tutoring_session.tutor.photo)) %>" alt="Avatar">
      <% else%>
        <img class="avatar_photo_smaller" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
      <% end%>
      <h1><%= tutoring_session.tutor.full_name %></h1>
    </div>
    <h1><%= tutoring_session.start_time.utc.strftime("%A, ") %> at <%= tutoring_session.start_time.utc.strftime("%H:%M") %></h1>
    <%= button_to "Cancel", cancel_session_path, method: :post,params:{tutoring_session_id: tutoring_session.id},class:"cancel_button"%>
  </div>
<% end%>
<div class="previous_tutoring_sessions">
  <h1>Previous Tutoring Sessions</h1>
</div>
<% timenow=DateTime.now %>
<% timenow=DateTime.new(timenow.year,timenow.month,timenow.day,timenow.hour,timenow.min) %>
<% checked_value=TutoringSession.where("start_time < ?", timenow)%>
<% upcoming_session=checked_value.where(user_id:@user) %>
<% upcoming_session.each do |tutoring_session|%>
  <div class="tutoring_sessions_times">
    <div class="tutoring_session_name_photo">
      <% if tutoring_session.tutor.photo.attached? %>
        <img class="avatar_photo_smaller" src="<%= (url_for(tutoring_session.tutor.photo)) %>" alt="Avatar">
      <% else%>
        <img class="avatar_photo_smaller" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
      <% end%>
      <h1><%= tutoring_session.tutor.full_name %></h1>
    </div>
    <h1><%= tutoring_session.start_time.utc.strftime("%A, %B %-d") %> at <%= tutoring_session.start_time.utc.strftime("%H:%M") %></h1>
  </div>
<% end%>