config/routes.rb
Rails.application.routes.draw do
  
  resources :tutors
  resources :users

  root 'home#index'

  get '/login_tutor', to: 'tutor_sessions#new',as: :login_tutor
  post '/login_tutor', to: 'tutor_sessions#create'
  get 'tutors/:id/my_page', to: 'tutors#my_page', as: :my_page

  delete 'logout', to: 'tutor_sessions#destroy', as: 'logout'
  

  get '/login_user', to: 'user_sessions#new',as: :login_user
  post '/login_user', to: 'user_sessions#create'
  post "/schedule_session", to: "tutors#schedule_session", as: :schedule_session
  post "/cancel_session",to: "tutors#cancel_session", as: :cancel_session
  delete 'logout_user', to: 'user_sessions#destroy', as: 'user_logout'
  post 'dismiss_notifications', to: 'user_sessions#dismiss_notifications', as: 'dismiss_notifications'


  post "/make_available", to: "tutors#make_available", as: :available_session
  post "/make_unavailable", to: "tutors#make_unavailable", as: :unavailable_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2TutoringService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if session[:user_id]%>
      <ul class="navbar_man">
        <li id="logotutor"><a href="<%= tutors_path %>">Learn<span class="ourlogo">Connect</span></a></li>
        <li><%= link_to "Home", tutors_path %></li>
        <li><%= link_to "My Page", current_user %></li>
        <li class="logout" style="margin-left:auto;"><%=link_to "Log Out", user_logout_path , method: :delete%></li>
      </ul>
    <% elsif session[:tutor_id] %>
      <ul class="navbar_man">
        <li id="logotutor"><a href="<%= my_page_path(current_tutor) %>">Learn<span class="ourlogo">Connect</span></a></li>
        <li><%= link_to "My Page", my_page_path(current_tutor) %></li>
        <li class="logout" style="margin-left:auto;"><%=link_to "Log Out", logout_path , method: :delete%></li>
      </ul>
    <% end%>
    <% if current_tutor %>
      <% if current_tutor.photo.attached? %>
        <%= link_to my_page_path(current_tutor) do %>
          <img class="thumbnailphoto" src="<%= (url_for(current_tutor.photo)) %>" alt="Avatar">
        <% end %>
      <% else%>
        <%= link_to my_page_path(current_tutor) do %>
          <img class="thumbnailphoto" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
        <% end %>
      <% end%>
    <% elsif current_user%>
      <% if current_user.photo.attached? %>
        <%= link_to current_user do %>
          <img class="thumbnailphoto" src="<%= (url_for(current_user.photo)) %>" alt="Avatar">
        <% end %>
      <% else%>
        <%= link_to current_user do %>
          <img class="thumbnailphoto" src="https://fertilitynetworkuk.org/wp-content/uploads/2017/01/Facebook-no-profile-picture-icon-620x389.jpg" alt="Avatar">
        <% end%>
      <% end%>
    <% end%>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnConnect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>